In [ ]:
Why Numpy?

it is used for performing operations like arrays 

addition, subtraction,multiplication, to create some 

random numbers, create dummy values etc,. 

In [1]:
a = [1,2,3,4,5]
type(a)

list

In [4]:
import numpy as np
b = np.array(object = [1,2.5,3,4,5,4.5],dtype = None)
b

array([1. , 2.5, 3. , 4. , 5. , 4.5])

In [5]:
b+2

array([3. , 4.5, 5. , 6. , 7. , 6.5])

In [ ]:
List Vs Array

1) In list we cannot do element wise operation but in array we can
2) Array to list conversion is possible and also list to array conversion
    is also possible but we will lose the dimensions
3) List is heterogenous datatype but Numpy is a homogenous datatype.

In [6]:
l1 = [1,2,3,4,5]
type(l1)

list

In [10]:
list1 = np.array(l1)
type(list1)

numpy.ndarray

In [8]:
list1

array([1, 2, 3, 4, 5])

In [9]:
l2 = list(list1)
type(l2)
l2

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [11]:
arr_1 = np.array(object=[1,2.5,10,4.8,5],dtype = int)
print(arr_1)
print(type(arr_1))
print("no of dimention            :",arr_1.ndim)
print("no of elements             :",arr_1.size)
print("Index of the maximum number:",arr_1.argmax())
print(arr_1.shape)

[ 1  2 10  4  5]
<class 'numpy.ndarray'>
no of dimention            : 1
no of elements             : 5
Index of the maximum number: 2
(5,)


In [12]:
arr_2 = np.array ([[11,23],[45,87]])
arr_2

array([[11, 23],
       [45, 87]])

In [13]:
print(arr_2)
print(type(arr_2))
print("no of dimention            :",arr_2.ndim)
print("no of elements             :",arr_2.size)
print("Index of the maximum number:",arr_2.argmax())
print(arr_2.shape)

[[11 23]
 [45 87]]
<class 'numpy.ndarray'>
no of dimention            : 2
no of elements             : 4
Index of the maximum number: 3
(2, 2)


In [3]:
import numpy as np

In [4]:
arr1 = np.array([[11,12,13,14],[25,26,27,28],[31,34,36,39]])
arr1

array([[11, 12, 13, 14],
       [25, 26, 27, 28],
       [31, 34, 36, 39]])

In [44]:
#reshaping arrays

np.reshape(arr1,(4,3))

array([[11, 12, 13],
       [14, 25, 26],
       [27, 28, 31],
       [34, 36, 39]])

In [45]:
np.reshape(arr1,(2,6))

array([[11, 12, 13, 14, 25, 26],
       [27, 28, 31, 34, 36, 39]])

In [46]:
arr1.flatten() #will get single row of elements

array([11, 12, 13, 14, 25, 26, 27, 28, 31, 34, 36, 39])

In [19]:
arr1[1,2] #Accesing element in an array

np.int64(27)

In [20]:
arr1[1][2]

np.int64(27)

In [23]:
#accesing 11,12,25,26
arr1[:2,:2] #var[row,column]

array([[11, 12],
       [25, 26]])

In [24]:
#11,13,25,27,31,36

arr1[:,::2]

array([[11, 13],
       [25, 27],
       [31, 36]])

In [25]:
#26,27,34,36
arr1[-2::,1:3:]

array([[26, 27],
       [34, 36]])

In [27]:
arr2=np.array([[0,0,0],[0,0,0],[0,0,0]])
arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros((3,3),dtype=int) #zero matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones((3,3),dtype=int) #one matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
a1 = np.array([[1,9],[5,4]])
a1

array([[1, 9],
       [5, 4]])

In [36]:
a2 = np.array([[2,4],[6,8]])
a2

array([[2, 4],
       [6, 8]])

In [37]:
a1+a2

array([[ 3, 13],
       [11, 12]])

In [38]:
a1-a2

array([[-1,  5],
       [-1, -4]])

In [39]:
a1*a2

array([[ 2, 36],
       [30, 32]])

In [ ]:
rule of matrix multiplication 
1st matrix cols = 2 matrix rows
(2x2),(2x2)

In [40]:
np.matmul(a1,a2)

array([[56, 76],
       [34, 52]])

In [41]:
np.identity(3,dtype=int) #all identity matrix will have same no of rows and columns so we need to mention olly no of rows 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.eye(3,dtype=int) #same as identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
np.full((3,2),4) #if you want 3x2 matrix of number 4

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
universal functions:

np.sqrt
exp() =
log()
sin()
mean()
median()
std()

In [47]:
arr1.mean()

np.float64(24.666666666666668)

In [52]:
arr1.std()

np.float64(9.472181492255215)

In [53]:
arr1 = np.sqrt

In [54]:
arr1

<ufunc 'sqrt'>