In [1]:
import pandas as pd

In [2]:
clm = pd.read_csv("claimants.csv")
clm

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...,...
1335,34100,1,0.0,1.0,0.0,NaN,0.576
1336,34110,0,1.0,1.0,0.0,46.0,3.705
1337,34113,1,1.0,1.0,0.0,39.0,0.099
1338,34145,0,1.0,0.0,0.0,8.0,3.177


In [3]:
del clm['CASENUM']

In [4]:
clm

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0,0.0,1.0,0.0,50.0,34.940
1,1,1.0,0.0,0.0,18.0,0.891
2,1,0.0,1.0,0.0,5.0,0.330
3,0,0.0,1.0,1.0,31.0,0.037
4,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...
1335,1,0.0,1.0,0.0,NaN,0.576
1336,0,1.0,1.0,0.0,46.0,3.705
1337,1,1.0,1.0,0.0,39.0,0.099
1338,0,1.0,0.0,0.0,8.0,3.177


In [5]:
clm.shape

(1340, 6)

In [6]:
clm.dtypes

ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [7]:
clm.isna().sum()

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [8]:
12+41+48+189

290

In [9]:
1340-290

1050

In [10]:
clm.dropna(inplace=True)
clm.reset_index(inplace=True)

In [11]:
del clm['index']

In [13]:
clm

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0,0.0,1.0,0.0,50.0,34.940
1,1,1.0,0.0,0.0,18.0,0.891
2,1,0.0,1.0,0.0,5.0,0.330
3,0,0.0,1.0,1.0,31.0,0.037
4,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...
1091,1,1.0,1.0,0.0,16.0,0.060
1092,0,1.0,1.0,0.0,46.0,3.705
1093,1,1.0,1.0,0.0,39.0,0.099
1094,0,1.0,0.0,0.0,8.0,3.177


In [14]:
clm.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [15]:
clm.describe(include='all')

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000
mean,0.472628,0.564781,0.904197,0.018248,28.587591,3.856578
std,0.499478,0.496012,0.294455,0.133909,20.392621,10.473239
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,9.000000,0.440000
50%,0.000000,1.000000,1.000000,0.000000,30.000000,1.311000
75%,1.000000,1.000000,1.000000,0.000000,43.000000,3.910500
max,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000


In [21]:
clm.duplicated().sum()

np.int64(8)

In [26]:
clm.drop_duplicates(inplace=True)

In [27]:
x = clm.iloc[:,1:]
x

,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0.0,1.0,0.0,50.0,34.940
1,1.0,0.0,0.0,18.0,0.891
2,0.0,1.0,0.0,5.0,0.330
3,0.0,1.0,1.0,31.0,0.037
4,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...
1091,1.0,1.0,0.0,16.0,0.060
1092,1.0,1.0,0.0,46.0,3.705
1093,1.0,1.0,0.0,39.0,0.099
1094,1.0,0.0,0.0,8.0,3.177


In [28]:
y = clm.iloc[:,0]
y

0       0
1       1
2       1
3       0
4       1
       ..
1091    1
1092    0
1093    1
1094    0
1095    1
Name: ATTORNEY, Length: 1088, dtype: int64

In [29]:
y.unique()

array([0, 1])

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,shuffle=True,random_state=16)

In [32]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((870, 5), (218, 5), (870,), (218,))

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_train_pred = lr.predict(x_train)
y_test_pred = lr.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [36]:
confusion_matrix(y_train,y_train_pred)

array([[293, 161],
       [ 92, 324]])

In [ ]:
acc = 0.715
recall = 0.718
precision = 0.720
f1 score = 0.718

In [37]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.76      0.65      0.70       454
           1       0.67      0.78      0.72       416

    accuracy                           0.71       870
   macro avg       0.71      0.71      0.71       870
weighted avg       0.72      0.71      0.71       870



In [38]:
confusion_matrix(y_test,y_test_pred)

array([[85, 35],
       [26, 72]])

In [39]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.77      0.71      0.74       120
           1       0.67      0.73      0.70        98

    accuracy                           0.72       218
   macro avg       0.72      0.72      0.72       218
weighted avg       0.72      0.72      0.72       218



In [40]:
# balanced class and imbalanced class
clm['ATTORNEY'].unique()

array([0, 1])

In [41]:
clm['ATTORNEY'].value_counts()

ATTORNEY
0    574
1    514
Name: count, dtype: int64

In [42]:
clm['ATTORNEY'].value_counts()[0]/1096

np.float64(0.5237226277372263)

In [43]:
clm['ATTORNEY'].value_counts()[1]/1096

np.float64(0.46897810218978103)

In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression

In [83]:
iris = pd.read_csv("Iris.csv")

In [84]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [85]:
iris.drop("Id",axis=1)

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [86]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [87]:
iris.duplicated().sum()

np.int64(0)

In [88]:
iris["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [89]:
le = LabelEncoder()
iris["Species"] = le.fit_transform(iris["Species"])

In [90]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,0
1,2,4.9,3.0,1.4,0.2,0
2,3,4.7,3.2,1.3,0.2,0
3,4,4.6,3.1,1.5,0.2,0
4,5,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,2
146,147,6.3,2.5,5.0,1.9,2
147,148,6.5,3.0,5.2,2.0,2
148,149,6.2,3.4,5.4,2.3,2


In [91]:
x = iris.drop("Species",axis=1)

In [92]:
y = iris["Species"]

In [111]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [112]:
x_train,x_test,y_train,y_test

(      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 22    23            4.6           3.6            1.0           0.2
 15    16            5.7           4.4            1.5           0.4
 65    66            6.7           3.1            4.4           1.4
 11    12            4.8           3.4            1.6           0.2
 42    43            4.4           3.2            1.3           0.2
 ..   ...            ...           ...            ...           ...
 71    72            6.1           2.8            4.0           1.3
 106  107            4.9           2.5            4.5           1.7
 14    15            5.8           4.0            1.2           0.2
 92    93            5.8           2.6            4.0           1.2
 102  103            7.1           3.0            5.9           2.1
 
 [120 rows x 5 columns],
       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 73    74            6.1           2.8            4.7           1.2
 18    19            

In [94]:
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [95]:
y_pred_train 

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [96]:
y_pred_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [97]:
accuracy_score(y_train,y_pred_train)

1.0

In [98]:
confusion_matrix(y_train,y_pred_train)

array([[40,  0,  0],
       [ 0, 41,  0],
       [ 0,  0, 39]])

In [99]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        41
           2       1.00      1.00      1.00        39

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [100]:
accuracy_score(y_test,y_pred_test)

1.0

In [101]:
confusion_matrix(y_test,y_pred_test)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [102]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [114]:
f1_score(y_test,y_pred_test,average="macro")

1.0

In [115]:
recall_score(y_test,y_pred_test,average="macro")

1.0